version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: sending
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - djangonetwork
    restart: always
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - djangonetwork
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django-backend-container
    volumes:
      - ./backend:/app 
    environment:
      - DJANGO_ALLOWED_HOSTS=127.0.0.1,localhost
      - CELERY_BROKER_URL=redis://redis:6379/2
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    command:
      - sh
      - -c
      - |
        /usr/local/bin/wait-for-it.sh db:5432 -t 25 --
        /usr/local/bin/wait-for-it.sh redis:6379 -t 10 --
        python manage.py makemigrations --noinput
        python manage.py migrate --noinput
        python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    links:
      - db:db
      - redis:redis
    networks:
      - djangonetwork
  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - /app
    command: 
      - sh
      - -c
      - start-celery.sh
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/2
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    ports:
      - "5555:5555"
    depends_on:
      - db
      - redis
      - web
    networks:
      - djangonetwork
volumes:
  pgdbdata: null
networks:
  djangonetwork:
    driver: bridge