# Generated by Django 4.2.6 on 2023-11-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientstuff', '0001_initial'),
        ('sending', '0002_alter_message_sending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfilter',
            name='mob_operator_code',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('sending', 'client')},
        ),
    ]
