# Generated by Django 4.2.6 on 2023-11-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sending', '0003_alter_clientfilter_mob_operator_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sending',
            name='celery_id',
        ),
        migrations.AddField(
            model_name='message',
            name='celery_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='revoke_celery_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
