# Generated by Django 4.2.6 on 2023-11-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.PositiveBigIntegerField(error_messages={'unique': 'Данный номер телефона уже зарегистрирован'}, unique=True)),
                ('mob_operator_code', models.CharField(max_length=3)),
                ('tag', models.CharField(max_length=255, null=True)),
                ('timezone', models.CharField(max_length=255)),
            ],
        ),
    ]
